### ISSUE TITLE
Errror

### ISSUE THREAD

**Issue by kkaru** [Yootah/TU-Projekti-Repo#24]
Krt level tuli võimatu, pidin mängu resama neljanda leveli keskelt!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by kkaru** [comment]
Print sreen levelist (tegelt oli 1. level) http://imgur.com/HealDGL

**Comment by kkaru** [comment]
Never mind, saime edasi siit kohast.

**Comment by Yootah** [comment]
eee... tere @kkaru  :D
kas miski tahab parandamist?

**Comment by kkaru** [comment]
Ei, tegelikult oli kõik korras, sain läbi tehtud.
